<#
.SYNOPSIS
  Merge the GitHub_Learning curriculum (Phase0..Phase10) into the MkDocs book
  as Phase 8..18 of Part I (Hands-On).

.DESCRIPTION
  Idempotent. Copies each Phase folder with a renumbered name into
  docs/PartI_HandsOn/, rewrites internal links so they continue to resolve
  inside MkDocs, and emits a nav fragment to tools/_nav_GitHub.yml.

.NOTES
  Invoke with PowerShell 7:
    pwsh -NoProfile -File .\tools\Merge-GitHubLearning.ps1
#>

[CmdletBinding()]
param(
    [string]$SourceRoot = (Join-Path (Resolve-Path "$PSScriptRoot\..\..").Path 'GitHub_Learning'),
    [string]$Destination = (Join-Path (Resolve-Path "$PSScriptRoot\..").Path 'docs\PartI_HandsOn'),
    [string]$NavOut = (Join-Path $PSScriptRoot '_nav_GitHub.yml')
)

$ErrorActionPreference = 'Stop'

# Old folder name -> New folder name (under docs/PartI_HandsOn/)
$Mapping = [ordered]@{
    'Phase0_Setup'              = 'Phase8_GitHub_Setup'
    'Phase1_Git_Fundamentals'   = 'Phase9_Git_Fundamentals'
    'Phase2_GitHub_Basics'      = 'Phase10_GitHub_Basics'
    'Phase3_Intermediate_Git'   = 'Phase11_Intermediate_Git'
    'Phase4_GitHub_Actions'     = 'Phase12_GitHub_Actions'
    'Phase5_Copilot_GenAI'      = 'Phase13_Copilot_GenAI'
    'Phase6_Copilot_CLI'        = 'Phase14_Copilot_CLI'
    'Phase7_Agentic_AI_Copilot' = 'Phase15_Agentic_AI_Copilot'
    'Phase8_GHAS_Admin'         = 'Phase16_GHAS_Admin'
    'Phase9_ExamPrep'           = 'Phase17_ExamPrep'
    'Phase10_Capstone'          = 'Phase18_Capstone'
}

# Nav title overrides for each new folder
$NavTitles = [ordered]@{
    'Phase8_GitHub_Setup'        = 'Phase 8 - GitHub Setup'
    'Phase9_Git_Fundamentals'    = 'Phase 9 - Git Fundamentals'
    'Phase10_GitHub_Basics'      = 'Phase 10 - GitHub Basics'
    'Phase11_Intermediate_Git'   = 'Phase 11 - Intermediate Git'
    'Phase12_GitHub_Actions'     = 'Phase 12 - GitHub Actions'
    'Phase13_Copilot_GenAI'      = 'Phase 13 - Copilot + GenAI'
    'Phase14_Copilot_CLI'        = 'Phase 14 - Copilot CLI'
    'Phase15_Agentic_AI_Copilot' = 'Phase 15 - Agentic AI with Copilot'
    'Phase16_GHAS_Admin'         = 'Phase 16 - GHAS Admin & Security'
    'Phase17_ExamPrep'           = 'Phase 17 - Exam Prep'
    'Phase18_Capstone'           = 'Phase 18 - Capstone'
}

if (-not (Test-Path $SourceRoot)) {
    throw "Source root not found: $SourceRoot"
}

# Ensure destination exists
$null = New-Item -ItemType Directory -Path $Destination -Force

function Convert-LinksInContent {
    param(
        [string]$Text
    )
    # 1) Rewrite ../PhaseN_X/README.md -> ../PhaseM_Y/README.md
    foreach ($k in $Mapping.Keys) {
        $newName = $Mapping[$k]
        $Text = $Text -replace ([regex]::Escape("../$k/")), "../$newName/"
        $Text = $Text -replace ([regex]::Escape("$k/")), "$newName/"
    }
    # 2) README.md was renamed to index.md inside each phase folder
    $Text = $Text -replace '/README\.md(?=[)#])', '/index.md'
    $Text = $Text -replace '\(\.\./README\.md\)', '(../index.md)'
    # 3) Rewrite references to the mdBook companion files that don't exist in MkDocs
    $Text = $Text -replace '\(\.\./BOOK\.md[^)]*\)', '(../index.md)'
    $Text = $Text -replace '\(\.\./EXAM_BLUEPRINT\.md[^)]*\)', '(../index.md)'
    $Text = $Text -replace '\(\.\./SETUP\.md[^)]*\)', '(../../SETUP.md)'
    $Text = $Text -replace '\(\.\./CONTRIBUTING\.md[^)]*\)', '(../CONTRIBUTING.md)'
    $Text = $Text -replace '\(\.\./LICENSE[^)]*\)', '(https://github.com/mail2raji/genai-agentic-ai-handbook/blob/main/LICENSE)'
    return $Text
}

$utf8 = New-Object System.Text.UTF8Encoding $false

$navLines = New-Object System.Collections.Generic.List[string]
$navLines.Add('# Auto-generated by Merge-GitHubLearning.ps1 - do not hand-edit.')
$navLines.Add('# Splice this into mkdocs.yml under Part I.')

foreach ($entry in $Mapping.GetEnumerator()) {
    $srcName = $entry.Key
    $dstName = $entry.Value
    $src = Join-Path $SourceRoot $srcName
    if (-not (Test-Path $src)) {
        Write-Warning "Source folder missing, skipping: $src"
        continue
    }
    $dst = Join-Path $Destination $dstName
    $null = New-Item -ItemType Directory -Path $dst -Force

    Write-Host "==> $srcName  ->  $dstName" -ForegroundColor Cyan

    $title = $NavTitles[$dstName]
    $navLines.Add(('      - "{0}":' -f $title))

    # Order: README.md (overview) first, then exercises.md, then anything else
    $files = Get-ChildItem -Path $src -File | Sort-Object @{
        Expression = {
            switch -Regex ($_.Name) {
                '^README\.md$'     { 0; break }
                '^exercises\.md$'  { 1; break }
                default             { 2 }
            }
        }
    }, Name

    foreach ($f in $files) {
        $relName = $f.Name
        # Skip non-md / non-text artefacts; the source only has .md files anyway
        if ($f.Extension -notin @('.md', '.markdown')) {
            Copy-Item $f.FullName -Destination (Join-Path $dst $relName) -Force
            continue
        }

        $raw = [IO.File]::ReadAllText($f.FullName)
        $rewritten = Convert-LinksInContent -Text $raw

        $outName = $relName
        # Friendly rename: README.md -> index.md so the phase folder gets a clean URL
        if ($relName -ieq 'README.md') { $outName = 'index.md' }

        $outPath = Join-Path $dst $outName
        [IO.File]::WriteAllText($outPath, $rewritten, $utf8)

        # Build a nav label
        $label = switch ($outName) {
            'index.md'      { 'Overview' }
            'exercises.md'  { 'Exercises' }
            default {
                # Title-case from filename
                $b = [IO.Path]::GetFileNameWithoutExtension($outName)
                ($b -split '[_\-]' | ForEach-Object {
                    if ($_.Length -gt 0) { $_.Substring(0,1).ToUpper() + $_.Substring(1) } else { $_ }
                }) -join ' '
            }
        }

        # Phase 8 + label is rendered as "0. Overview" / "1. Exercises" for visual consistency with existing phases
        $idx = if ($outName -eq 'index.md') { '0. ' } elseif ($outName -eq 'exercises.md') { '1. ' } else { '' }
        $navPath = "PartI_HandsOn/$dstName/$outName"
        $navLines.Add(('          - "{0}{1}": {2}' -f $idx, $label, $navPath))
    }
}

[IO.File]::WriteAllText($NavOut, ($navLines -join "`n"), $utf8)

Write-Host ""
Write-Host "Done."
Write-Host "Nav fragment written to: $NavOut"
$leafCount = ($navLines | Where-Object { $_ -match '^\s{10}- "' }).Count
Write-Host "Phase folders: $($Mapping.Count) - Leaf nav entries: $leafCount"
